name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Pypy3.10
        uses: actions/setup-python@v5
        with:
          python-version: "pypy3.10"

      - name: Install Python dependencies
        run: |
          pypy3 -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install C dependencies
        run: |
          sudo apt-get install build-essential  # For Ubuntu
          
      - name: Run pylint
        run: |
          pylint --fail-under=9 src/

      - name: Format python code with ruff
        run: pypy3 -m ruff format
        
      - name: Build and run tests
        run: |
          make test  # Adjust to your testing process

      - name: Cleanup
        run: |
          make clean
